ekf_gps:
  frequency: 10.0
  sensor_timeout: 0.1
  two_d_mode: false
  transform_time_offset: 0.0
  transform_timeout: 0.0
  map_frame: "map"
  odom_frame: "odom"
  base_link_frame: "base_link"
  world_frame: "odom"

  odom1: "/jackal_velocity_controller/odom"
  odom1_config: [false, false, false,
                 false, false, true,
                 true, true, true,
                 false, false, true,
                 false, false, false]
  odom1_differential: true

  imu0: "/imu/data"
  imu0_config: [false, false, false,
                true, true, true,
                false, false, false,
                false, false, false,
                false, false, false]

  odom2: "/odometry/gps"
  odom2_config: [true, true, true,
                 false, false, false,
                 false, false, false,
                 false, false, false,
                 false, false, false]
